### ISSUE TITLE
Error with screen_size() in Windows

### ISSUE THREAD

**Issue by gsbabil** [pepijndevos/PyMouse#12]
Hi, I am getting errors as following on Windows when calling `screen_size()`:

``` Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymouse\windows.py", line 49, in screen_size
    def screen_size(self):
NameError: global name 'GetSystemMetrics' is not defined
```

It was fixed by replacing the `screen_size()` inside window.py with the following:

```
    def screen_size(self):
        width = windll.user32.GetSystemMetrics(0)
        height = windll.user32.GetSystemMetrics(1)
        return width, height
```

**Comment by pepijndevos** [comment]
I don't really maintain PyMouse anymore, and I don't have a Windows box, but if you test it a bit and submit a pull request, I can merge it.
